version: "3"

# ========= 変数 =========
vars:
  # バケット名（.envで設定したものを使う）
  BACKEND_BUCKET:
    sh: "echo ${TF_BACKEND_BUCKET}"

# ========= タスク一覧 =========
tasks:
  # 初期設定（バケット作成と terraform init）
  setup-backend:
    desc: "最初の準備：バケット作成 + Terraform 初期化"
    cmds:
      - ./setup-backend.sh # バケットを作成
      - |
        terraform -chdir=secrets init \
          -backend-config="bucket={{.BACKEND_BUCKET}}" \
          -backend-config="prefix=n8n-secrets"
      - |
        terraform -chdir=project init \
          -backend-config="bucket={{.BACKEND_BUCKET}}" \
          -backend-config="prefix=n8n"

  # Supabase 情報（secrets）を plan
  plan-secrets:
    desc: "Supabase 情報の変更確認（plan）"
    cmds:
      - terraform -chdir=secrets plan -var-file=terraform.tfvars

  # n8n本体の構成（project）を plan
  plan-app:
    desc: "n8n アプリ構成の変更確認（plan）"
    cmds:
      - terraform -chdir=project plan

  # Supabase 情報（secrets）を apply（手動確認あり）
  deploy-secrets:
    desc: "Supabase 情報のデプロイ（確認あり）"
    cmds:
      - terraform -chdir=secrets apply -var-file=terraform.tfvars

  # Supabase 情報を apply（確認なしで自動実行）
  deploy-secrets-auto:
    desc: "Supabase 情報のデプロイ（自動実行）"
    cmds:
      - terraform -chdir=secrets apply -auto-approve -var-file=terraform.tfvars

  # n8n構成を apply（Cloud Run のURLを自動反映）
  deploy-app:
    desc: "n8n アプリのデプロイ（確認あり）＋URL再設定"
    cmds:
      - terraform -chdir=project apply
      - |
        # URL を取得して再 apply
        URL=$(terraform -chdir=project output -raw service_url 2>/dev/null || true); \
        if echo "$URL" | grep -E '^https?://' >/dev/null; then \
          HOST=${URL#https://}; HOST=${HOST#http://}; \
          echo "Cloud Run URL: $URL"; \
          terraform -chdir=project apply \
            -var="n8n_host=${HOST}" -var="n8n_editor_base_url=${URL}"; \
        else \
          echo "Cloud Run のURLが見つからないのでスキップします"; \
        fi

  # n8n構成を apply（確認なしで自動実行）
  deploy-app-auto:
    desc: "n8n アプリのデプロイ（自動実行）＋URL反映"
    cmds:
      - terraform -chdir=project apply -auto-approve
      - |
        # URL を取得して再 apply（自動）
        URL=$(terraform -chdir=project output -raw service_url 2>/dev/null || true); \
        if echo "$URL" | grep -E '^https?://' >/dev/null; then \
          HOST=${URL#https://}; HOST=${HOST#http://}; \
          echo "Cloud Run URL: $URL"; \
          terraform -chdir=project apply -auto-approve \
            -var="n8n_host=${HOST}" -var="n8n_editor_base_url=${URL}"; \
        else \
          echo "Cloud Run のURLが見つからないのでスキップします"; \
        fi

  # 一括デプロイ（初期化からapplyまで全自動）
  deploy-all:
    desc: "一発デプロイ（setup-backend → deploy 全自動）"
    cmds:
    - task: setup-backend
    - task: deploy-secrets-auto
    - task: deploy-app-auto

  # n8n 構成を削除（確認あり）
  destroy-app:
    desc: "n8n アプリの構成を削除"
    cmds:
      - |
        terraform -chdir=project init -reconfigure \
          -backend-config="bucket={{.BACKEND_BUCKET}}" \
          -backend-config="prefix=n8n"
      - terraform -chdir=project destroy

  # Supabase 情報を削除（確認あり）
  destroy-secrets:
    desc: "Supabase 情報を削除"
    cmds:
      - |
        terraform -chdir=secrets init -reconfigure \
          -backend-config="bucket={{.BACKEND_BUCKET}}" \
          -backend-config="prefix=n8n-secrets"
      - terraform -chdir=secrets destroy -var-file=terraform.tfvars

  # 全部まとめて削除（n8n → Supabase の順）
  destroy-all:
    desc: "全て削除（n8n → Supabase）"
    cmds:
    - task: destroy-app
      - task: destroy-secrets
